version: '3'
services:
  nginx:
    restart: always
    image: nginx:1.18.0 # 镜像名，根据实际情况修改
    privileged: true
    container_name: nginx
    ports:
      - '80:80' # 映射端口
    dns:
      - 114.114.114.114
    links:
      - 'php-dev'
    volumes: # 挂载目录根据实际情况修改
      - E:/workspace/dev/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - E:/workspace/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - E:/workspace/ymserp:/var/www/html/ymserp:ro
      - E:/workspace/ymserp/runtime:/var/www/html/ymserp/runtime:rw
      - E:/workspace/ymserp/public:/var/www/html/ymserp/public:rw
      - E:/workspace/erp-vue-release:/var/www/html/erp-vue-release:ro
    command: [nginx, '-g', 'daemon off;']
  php-dev:
    restart: always
    image: php-dev:latest # 镜像名，根据实际情况修改
    privileged: true
    container_name: php-dev
    dns:
      - 114.114.114.114
    volumes: # 挂载目录根据实际情况修改
      - E:/workspace/ymserp:/var/www/html/ymserp/:rw